[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "DkbxoQxhdgYDcxySw2s2uyL57xxX8qqbh549cGZcJUmA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/i/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
